add doc operations
marcaudefroy/api-domain-ovh pull request #2
Opened 2022-03-10 13:34 UTC by Thiht

2022-03-10 14:13 UTC, marcaudefroy commented on docs/fr/operations.md
> +- `DomainTrade` : changement de contact propriétaire. Les erreurs seront généralement liées à des incompatibilités d'éligibilité sur le contact receveur.
DomainsDnsUpdate aussi :)

2022-03-10 14:21 UTC, gwleclerc requested changes

2022-03-10 14:21 UTC, gwleclerc commented on docs/fr/operations.md
> +| `status`   |      ✗      | Statut des opérations ) récupérer                |
```suggestion
| `status`   |      ✗      | Statut des opérations à récupérer                |
```

2022-03-10 14:21 UTC, gwleclerc commented on docs/fr/operations.md
> +La plupart des actions effectuées sur les noms de domaines se traduisent par des modifications chez le OVHcloud, ainsi que chez le registre.
```suggestion
La plupart des actions effectuées sur les noms de domaines se traduisent par des modifications chez le registrar (OVHcloud), ainsi que chez le registre.
```

2022-03-10 14:21 UTC, gwleclerc commented on docs/fr/operations.md
> +Par souci de robustesse et de performance, elles sont donc lancées de manière asynchrones.
```suggestion
Par souci de robustesse et de performance, elles sont lancées de manière asynchrones.
```

2022-03-10 14:21 UTC, gwleclerc commented on docs/fr/operations.md
> +  2. Un problème est survenu du côté d'OVHcloud : dans ce cas vous ne pourrez pas relancer l'opération vous-même. L'opération sera relancée automatiquement périodiquement, mais vous devrez ouvrir une
```suggestion
  2. Un problème est survenu du côté d'OVHcloud : dans ce cas vous ne pourrez pas relancer l'opération vous-même. L'opération sera relancée périodiquement de manière automatique, mais vous devrez ouvrir une demande de support si malgré cela le problème persiste.
```

2022-03-10 14:21 UTC, gwleclerc commented on docs/fr/operations.md
> +- `DomainIncomingTransfer`, `DomainAfterMarket` : transfert d'un nom de domaine depuis un autre registrar ou un marché secondaire. Les erreurs seront généralement liées à la demande de l'auth code pe
```suggestion
- `DomainIncomingTransfer`, `DomainAfterMarket` : transfert d'un nom de domaine depuis un autre registrar ou un marché secondaire. Les erreurs seront généralement liées à la demande de l'`authCode` permettant la validation du transfert.
```

2022-03-10 14:24 UTC, Thiht commented on docs/fr/operations.md
> +- `DomainIncomingTransfer`, `DomainAfterMarket` : transfert d'un nom de domaine depuis un autre registrar ou un marché secondaire. Les erreurs seront généralement liées à la demande de l'auth code pe
j'ai regardé les autres registrars, ionos et gandi ils mettent "auth code"

2022-03-10 14:26 UTC, gwleclerc commented on docs/fr/operations.md
> +- `DomainIncomingTransfer`, `DomainAfterMarket` : transfert d'un nom de domaine depuis un autre registrar ou un marché secondaire. Les erreurs seront généralement liées à la demande de l'auth code pe
ok mais garde l'emphase quand même

2022-03-10 16:26 UTC, moyjunior commented on docs/fr/operations.md
> +Par souci de robustesse et de performance, elles sont donc lancées de manière asynchrones.
asynchrone

2022-03-11 15:34 UTC, gwleclerc approved these changes

2022-03-11 16:03 UTC, benoitmasson commented
attention au chemin vers la doc anglaise, c'est dans les fichiers `/docs/`, pas dans `/docs/en/` car c'est la version par défaut (cf. [config.js](https://github.com/marcaudefroy/api-domain-ovh/pull/4/files#diff-52eb86351480925d61947a58caca1ea76d10950ec26533f16f37cb12a3519dff))

2022-03-11 16:03 UTC, benoitmasson commented on docs/en/operations.md
> +- `todo`: the operation has been created but is not currently being treated. Most operations (`DomainCreate`, `DomainRenew`, etc.) are executed in the minute, and finalized in 5 to 10 minutes.
```suggestion
- `todo`: the operation has been created but is not currently being handled. Most operations (`DomainCreate`, `DomainRenew`, etc.) are executed in the minute, and finalized in 5 to 10 minutes.
```

2022-03-11 16:04 UTC, benoitmasson commented on docs/en/operations.md
> +- `done`: the operation terminated successfully. This is a final status.
```suggestion
- `done`: the operation completed successfully. This is a final status.
```

2022-03-11 16:04 UTC, benoitmasson commented on docs/fr/operations.md
> +Par souci de robustesse et de performance, elles sont lancées de manière asynchrones.
```suggestion
Par souci de robustesse et de performance, elles sont lancées de manière asynchrone.
```

2022-03-11 16:05 UTC, benoitmasson commented on docs/fr/operations.md
> +une **opération** est créée et permet de récupérer un statut, de modifier certaines données en cas d'erreur ou encore de relancer des actions après un échec,
```suggestion
une **opération** est créée et permet de récupérer un statut, de modifier certaines données en cas d'erreur ou encore de relancer des actions après un échec.
```

2022-03-11 16:05 UTC, benoitmasson commented on docs/fr/operations.md
> +Historiquement, les opérations OVHcloud sont manipulables sous deux chemins d'API distincts:
```suggestion
Historiquement, les opérations OVHcloud sont manipulables sous deux chemins d'API distincts :
```

2022-03-11 16:06 UTC, benoitmasson commented on docs/fr/operations.md
> +- `todo`: l'opération a été créée mais n'est pas en cours de traitement. La plupart des opérations (`DomainCreate`, `DomainRenew`, etc.) sont exécutées dans la minute, et finalisées dans les 5 à 10 m
```suggestion
- `todo` : l'opération a été créée mais n'est pas en cours de traitement. La plupart des opérations (`DomainCreate`, `DomainRenew`, etc.) sont exécutées dans la minute, et finalisées dans les 5 à 10 minutes.
```
`+` pareil sur tous les suivants, on met un espace (idéalement, insécable) avant les `:` en FR

2022-03-11 16:07 UTC, benoitmasson commented on docs/fr/operations.md
> +| `domain`   |      ✗      | Filtrer les opérations liées à ce nom de domaine |
c'est pas clair la croix… à la rigueur un check, mais moi dans la doc sur la commande, j'ai mis des "oui"/"non" (c'était des "true"/"false" avant)

2022-03-11 16:08 UTC, benoitmasson commented on docs/fr/operations.md
> +Pour récupérer les détails liés à une opération en particulier, vous pouvez utiliser l'API suivante:
```suggestion
Pour récupérer les détails liés à une opération en particulier, vous pouvez utiliser l'API suivante :
```

2022-03-11 16:09 UTC, benoitmasson commented on docs/fr/operations.md
> +Les champs les plus intéressants par cette API sont les suivants :
`+` un exemple de réponse au-dessus ?
cf. https://github.com/marcaudefroy/api-domain-ovh/blob/develop/docs/fr/order.md?plain=1#L102-L114

```suggestion
Les champs les plus intéressants dans la réponse sont les suivants :
```

2022-03-11 16:11 UTC, benoitmasson commented on docs/fr/operations.md
> +Pour modifier le champ `legitimacyAfnic`, il faudra utiliser l'API [`PUT /me/task/domain/{id}/argument/{key}`](https://eu.api.ovh.com/console/#/me/task/domain/%7Bid%7D/argument/%7Bkey%7D~PUT) en rens
précise un peu : nouvelle valeur => champ `value` du json, je mettrais même un exemple de payload pour lever toute ambiguïté

2022-03-11 16:11 UTC, benoitmasson commented on docs/fr/operations.md
> +Pour modifier le champ `legitimacyAfnic`, il faudra utiliser l'API [`PUT /me/task/domain/{id}/argument/{key}`](https://eu.api.ovh.com/console/#/me/task/domain/%7Bid%7D/argument/%7Bkey%7D~PUT) en rens
```suggestion
Pour modifier le champ `legitimacyAfnic`, il faudra utiliser l'API [`PUT /me/task/domain/{id}/argument/{key}`](https://eu.api.ovh.com/console/#/me/task/domain/%7Bid%7D/argument/%7Bkey%7D~PUT) en renseignant sa nouvelle valeur. Une fois la valeur modifiée, vous pourrez si vous le souhaitez réutiliser l'API [`GET /me/task/domain/{id}/argument/{key}`](https://eu.api.ovh.com/console/#/me/task/domain/%7Bid%7D/argument/%7Bkey%7D~GET) pour vérifier qu'elle a bien été prise en compte.
```

2022-03-11 16:13 UTC, benoitmasson commented on docs/fr/operations.md
> +Il existe un grand nombre de types d'opérations différentes (plus d'une trentaine), toutes ayant chacune leurs spécificités. En tant que client, vous n'aurez que rarement à intervenir sur celles-ci.
```suggestion
Il existe un grand nombre de types d'opérations différentes (plus d'une trentaine), toutes ayant leurs spécificités. En tant que client, vous n'aurez que rarement à intervenir sur celles-ci. Les plus communes sont cependant les suivantes :
```

2022-03-14 09:18 UTC, Thiht commented on docs/fr/operations.md
> +| `domain`   |      ✗      | Filtrer les opérations liées à ce nom de domaine |
je vais mettre des oui/non

2022-03-14 09:54 UTC, merged