Translate order
marcaudefroy/api-domain-ovh pull request #4
Opened 2022-03-10 16:44 UTC by benoitmasson

- Fix some typos and formatting on order FR page
- Translate to a new order EN page

2022-03-10 17:15 UTC, NoemieFo commented on docs/fr/order.md
>  - des APIs pour ajouter/supprimer une configuration associé au produit.
- des APIs pour ajouter/supprimer une configuration associée au produit.

2022-03-10 17:16 UTC, NoemieFo commented on docs/fr/order.md
>  1. Récupérer les configurations requise pour ce produit
```suggestion
1. Récupérer les configurations requises pour ce produit
```

2022-03-10 17:16 UTC, NoemieFo commented on docs/fr/order.md
>  - des APIs pour ajouter/supprimer une configuration associé au produit.
associéE

2022-03-10 17:16 UTC, NoemieFo commented on docs/fr/order.md
>  1. Récupérer les offres disponible pour le produit souhaité
disponibleS

2022-03-10 17:18 UTC, NoemieFo commented on docs/fr/order.md
> +La seconde étape consiste à récupérer les offres accessible pour un domaine.
```suggestion
La seconde étape consiste à récupérer les offres accessibles pour un domaine.
```

2022-03-10 17:19 UTC, NoemieFo commented on docs/fr/order.md
> +| domain    | oui    | ""     | le nom de domain souhaité |
Le nom de domain souhaité

2022-03-10 17:20 UTC, NoemieFo commented on docs/fr/order.md
> +2. La _duration_ : ce champs représente l'unite de période sur laquelle il est possible de commander le domaine. Pour un domaine, P1Y (period 1 year) équivaut à une période d'un an, P2Y une période d
ce champ représente l'unité de période sur laquelle il est possible de commander le domaine.

2022-03-10 17:21 UTC, NoemieFo commented on docs/fr/order.md
> +| create-défaut                                | Le domaine est libre et au prix standard
Les pricing mode sont traduits ?

2022-03-10 17:22 UTC, NoemieFo commented on docs/fr/order.md
> +La première consiste à avoir un mapping entre le pricing-mode et le statut du domaine. Voici ci-dessous cette table de mapping exhaustive.
Le premier (au dessus on parle de 2 moyens)

2022-03-10 17:22 UTC, NoemieFo commented on docs/fr/order.md
>  La deuxième, **déprécié et bientôt supprimé** consiste à analyser le couple pricing-mode/offerId.
Le deuxième

2022-03-10 17:23 UTC, NoemieFo commented on docs/fr/order.md
> +| défaut                     | \$extension-create (fr-create, com-create)       | Le domaine est libre et au prix standard
Même question, on traduit les pricing mode ?

2022-03-10 17:25 UTC, NoemieFo commented on docs/fr/order.md
> +    "pricingMode": "create-défaut",
Meme question pour la traduction

2022-03-10 17:26 UTC, NoemieFo commented on docs/fr/order.md
> +- Une ligne de detail est ajouté par promotion (`detailType` = `GIFT`)
ajoutéE

2022-03-10 17:26 UTC, NoemieFo commented on docs/fr/order.md
>  - La liste des contrats est vide lors du résumé. Elle sera remplit lors de la validation ou de la création du bon de commande.
rempliE

2022-03-10 17:27 UTC, NoemieFo commented on docs/fr/order.md
> +Une chose qui peut surprendre dans ce résumé est la présence d'une zone DNS (représentée par 2 lignes de détails) alors qu'elle n'a pas été ajoutée panier. Cela fait écho à une notion souvent méconnu
[...] notion souvent méconnuE [...] alors que la zone peut-être hébergéE autre part.

2022-03-10 17:28 UTC, NoemieFo commented on docs/fr/order.md
> +Cependant, les deux étant très liés et dans un but de faciliter la commande d'un nom de domaine, nous avons fait le choix d'ajouter automatiquement une zone à l'achat d'un nom de domaine. Bien sûr, i
[...] afin d'y ajouter des options telLEs que [...]

2022-03-10 17:29 UTC, NoemieFo commented on docs/fr/order.md
>  Bien que cette opération peut se faire dès la création du cart, elle devient indispensable à partir de maintenant. Nous le verrons par la suite, mais les configurations d'un nom de domaine et sa vali
Bien que cette opération PUISSE se faire dès la création du cart [...]
Nous le verrons par la suite, les configurations d'un nom de domaine et LEUR validation dépendENT du nic OVH.

2022-03-10 17:30 UTC, NoemieFo commented on docs/fr/order.md
>  La réponse ci-dessus représente l'exemple le plus commun que tu pourrras retrouvé lors de la commande de création d'un nom de domaine.
```suggestion
La réponse ci-dessus représente l'exemple le plus commun que tu pourras retrouver lors de la commande de création d'un nom de domaine.
```

2022-03-10 17:31 UTC, NoemieFo commented on docs/fr/order.md
> +Mais celle-ci dépend fortement de l'action désirée (transfert, création), de l'extension ou bien du type de domaine (premium, issue d'un marché secondaire)
issu (sans e)

2022-03-10 17:32 UTC, NoemieFo commented on docs/fr/order.md
> +| ADMIN_ACCOUNT     | string                         | non               | Représente le nic ovh qui pourra administrer le domaine et sera associé en tant qu'admin sur le whois. Si vide, le nic conne
```suggestion
| ADMIN_ACCOUNT     | string                         | non               | Représente le nic OVHcloud qui pourra administrer le domaine et sera associé en tant qu'admin sur le whois. Si vide, le nic connecté à l'API sera pris par défaut. La valeur attendue doit être un nic valide sous la forme xxx-ovh                                                                             |
```

2022-03-10 17:33 UTC, NoemieFo commented on docs/fr/order.md
> +| TECH_ACCOUNT      | string                         | non               | Représente le nic ovh qui pourra gérer techniquement le domaine et sera associé en tant que tech sur le whois. Si vide, le n
[...] le nic connecté à l'API sera pris paR défaut. La valeur attenduE doit être [...]

2022-03-10 17:34 UTC, NoemieFo commented on docs/fr/order.md
> +| OWNER_CONTACT     | /me/contact ou /domain/contact | non               | Représente le propriétaire du nom de domaine. Si vide, le nicadmin sera pris en modèle pour créer un contact. La valeur atte
La valeur attenduE est une chaÎne de CARACTèRES sous la forme [...]

2022-03-10 17:35 UTC, NoemieFo commented on docs/fr/order.md
> +| REASON            | string                         | oui si présent    | Il indique que le registre demande la raison pour laquelle le domaine veut être commandé. Cela concerne généralement des dom
[...] usages spécifiqueS [...]

2022-03-10 17:36 UTC, NoemieFo commented on docs/fr/order.md
> +| CLAIMS_NOTICE     | string                         | oui si présent    | Indique si un avis de marque est présente sur le domaine. Si oui, alors le domain est protégé par une marque et une notifica
Indique si un avis de marque est présent [...] Si oui, alors le domainE est protégé par une marque et une notification sera alors envoyéE au détenteur de la marque.

2022-03-10 17:41 UTC, NoemieFo commented on docs/fr/order.md
> +| défaut                     | \$extension-transfer (fr-transfer, com-transfer) | Le domaine n'est pas libre mais est transférable si vous en êtes le propriétaire. Son transfer est au prix standard.
```suggestion
| défaut                     | \$extension-transfer (fr-transfer, com-transfer) | Le domaine n'est pas libre mais est transférable si vous en êtes le propriétaire. Son transfert est au prix standard.                                       |
```

2022-03-10 17:41 UTC, NoemieFo commented on docs/fr/order.md
> +| premium                    | \$extension-transfer (fr-transfer, com-transfer) | Le domaine n'est pas libre mais est transférable si vous en êtes le propriétaire. C'est un domaine premium et son pri
```suggestion
| premium                    | \$extension-transfer (fr-transfer, com-transfer) | Le domaine n'est pas libre mais est transférable si vous en êtes le propriétaire. C'est un domaine premium et son prix est variable d'un domaine à l'autre. |
```

2022-03-10 17:41 UTC, NoemieFo commented on docs/fr/order.md
> +| aftermarket1, aftermarket2 | \$extension-transfer (fr-transfer, com-transfer) | Le domaine est libre via un marché secondaire. Son prix est variable d'un domaine à l'autre
```suggestion
| aftermarket1, aftermarket2 | \$extension-transfer (fr-transfer, com-transfer) | Le domaine est libre via un marché secondaire. Son prix est variable d'un domaine à l'autre.                                                               |
```

2022-03-10 17:42 UTC, NoemieFo commented on docs/fr/order.md
> +| pricingMode | non    |        | Représente l'offre lié au plan du domaine                                                                                                        |
```suggestion
| pricingMode | non    |        | Représente l'offre liée au plan du domaine                                                                                                        |
```

2022-03-10 17:52 UTC, NoemieFo commented on docs/fr/order.md
>  Pour connaître ces configurations requises, il suffit d'appeler l'API suivante.
```suggestion
Pour connaître les configurations requises, il suffit d'appeler l'API suivante.
```

2022-03-10 17:58 UTC, NoemieFo commented on docs/fr/order.md
> +| itemId    | oui    | ""     | L'identifiant de l'item inséré dans le cart |
On laisse cart ?

2022-03-10 18:04 UTC, NoemieFo commented on docs/fr/order.md
> +| PROTECTED_CODE    | string                         | oui si présent    | Certains domaines sont réservés par un registre et nécessite un code spécifique pour débloquer son obtention.
```suggestion
| PROTECTED_CODE    | string                         | oui si présent    | Certains domaines sont réservés par un registre et nécessitent un code spécifique pour débloquer leur obtention.                                                                                                                                                                                              |
```

2022-03-10 19:42 UTC, marcaudefroy commented on docs/fr/order.md
> +| create-défaut                                | Le domaine est libre et au prix standard
no, c'est des valeurs de l'api. ça devrait bien être "create-default"

2022-03-10 19:43 UTC, marcaudefroy commented on docs/fr/order.md
> +| défaut                     | \$extension-create (fr-create, com-create)       | Le domaine est libre et au prix standard
no : default

2022-03-11 08:50 UTC, benoitmasson commented on docs/fr/order.md
> +| create-défaut                                | Le domaine est libre et au prix standard
Mauvais replace-all, je les reprends tous 1 par 1 et je corrige. Merci

2022-03-11 09:36 UTC, benoitmasson commented on docs/fr/order.md
> +| itemId    | oui    | ""     | L'identifiant de l'item inséré dans le cart |
on parle de _panier_ dans l'intro, donc j'ai changé, merci

2022-03-11 09:38 UTC, benoitmasson commented on docs/fr/order.md
> +| aftermarket1, aftermarket2 | \$extension-transfer (fr-transfer, com-transfer) | Le domaine est libre via un marché secondaire. Son prix est variable d'un domaine à l'autre
j'ai supprimé tous les `.` finaux, plutôt (dans un tableau, je considère que c'est pas forcément une phrase

2022-03-11 09:48 UTC, benoitmasson commented on docs/fr/order.md
> +Cependant, les deux étant très liés et dans un but de faciliter la commande d'un nom de domaine, nous avons fait le choix d'ajouter automatiquement une zone à l'achat d'un nom de domaine. Bien sûr, i
reformulé

2022-03-11 15:33 UTC, NoemieFo commented on docs/fr/order.md
> +Attention, cette API est conçue pour répondre au besoin de la plupart des produits OVH. Cependant, les noms de domaine ont la particularité d'avoir des règles beaucoup plus complexe concernant la val
```suggestion
Attention, cette API est conçue pour répondre aux besoins de la plupart des produits OVHcloud. Cependant, les noms de domaine ont la particularité d'avoir des règles beaucoup plus complexes concernant la valeur de certaines configuration. Notamment sur les configurations ADMIN_ACCOUNT, OWNER_CONTACT ou encore DOMAIN_CONFIG, celles-ci étant liées à des règles de gestion de la part des registres.
```

2022-03-11 15:33 UTC, NoemieFo commented on docs/fr/order.md
>  Globalement, la commande d'un produit OVHcloud via l'API se fera toujours au travers de ces étapes:
```suggestion
Globalement, la commande d'un produit OVHcloud via l'API se fera toujours à travers ces étapes :
```

2022-03-11 15:33 UTC, NoemieFo commented on docs/fr/order.md
> +- L'ajout d'un item dans le panier produit 2 lignes de details sur le bon de commande
```suggestion
- L'ajout d'un item dans le panier produit deux lignes de details sur le bon de commande
```

2022-03-11 15:33 UTC, NoemieFo commented on docs/fr/order.md
> +- L'objet `prices` représente le total du panier avec ou sans taxe.
```suggestion
- L'objet `prices` représente le total du panier avec et sans taxe.
```
Ca me semble bizarre un "ou" ici

2022-03-11 15:33 UTC, NoemieFo commented on docs/fr/order.md
> +Une chose qui peut surprendre dans ce résumé est la présence d'une zone DNS (représentée par 2 lignes de détails) alors qu'elle n'a pas été ajoutée panier. Cela fait écho à une notion souvent méconnu
```suggestion
La présence d'une zone DNS (représentée par deux lignes de détails) alors qu'elle n'a pas été ajoutée au panier peut surprendre. Cela fait écho à une notion souvent méconnue, ou tout du moins, mal comprise. Une zone DNS et un domaine sont deux choses (produits) différentes. Un nom de domaine peut très bien être chez OVHcloud alors que la zone peut être hébergée autre part.
```

2022-03-11 15:33 UTC, NoemieFo commented on docs/fr/order.md
> +La réponse ci-dessus représente l'exemple le plus commun que tu pourras retrouver lors de la commande de création d'un nom de domaine.
```suggestion
La réponse ci-dessus représente l'exemple le plus commun que vous pourrez retrouver lors de la commande de création d'un nom de domaine.
```
On utilise "vous" au dessus

2022-03-11 15:33 UTC, NoemieFo commented on docs/fr/order.md
> +| ACCEPT_CONDITIONS | bool                           | oui si présent    | Indique que l'extension possède des conditions particulières à l'obtention de l'extension
Indique que l'obtention de l'extension est soumise à des conditions particulières

2022-03-11 15:33 UTC, NoemieFo commented on docs/fr/order.md
> +| OWNER_LEGAL_AGE   | bool                           | oui               | Toujours présent, il s'agit d'une configuration de type opt-in afin de certifier que le registrant à l'âge légal pour posséd
```suggestion
| OWNER_LEGAL_AGE   | bool                           | oui               | Toujours présent, il s'agit d'une configuration de type opt-in afin de certifier que le registrant a l'âge légal pour posséder un nom de domaine                                                                                                                                                           |
```

2022-03-11 15:33 UTC, NoemieFo commented on docs/fr/order.md
>  Cette étape est sans doute la plus importante du processus de commande et se fait via le call suivant.
Utiliser appel au lieu de call comme ligne 937 ?

2022-03-11 15:33 UTC, NoemieFo commented on docs/fr/order.md
> +Si vous n'avez pas payé le bon de commande automatiquement lors de la précédente étape, vous aurez besoin de manipuler les APIs de gestion des bons de commande. Bien qu'il existe de nombreuses APIs e
```suggestion
Si vous n'avez pas payé le bon de commande automatiquement lors de la précédente étape, vous aurez besoin de manipuler les APIs de gestion des bons de commande. Bien qu'il existe de nombreuses APIs en relation avec les moyens de paiement et la gestion des bons de commande, nous partirons du principe qu'au moins un moyen de paiement est enregistré sur votre compte.
```

2022-03-11 15:33 UTC, NoemieFo commented on docs/fr/order.md
> +Le paiement du bon de commande se fait via l'[API ci-dessous](https://api.ovh.com/console/#/me/order/{orderId}/payWithRegisteredPaymentMean#POST). Celle-ci ne retourne aucun résultat mais le status 2
```suggestion
Le paiement du bon de commande se fait via l'[API ci-dessous](https://api.ovh.com/console/#/me/order/{orderId}/payWithRegisteredPaymentMean#POST). Celle-ci ne retourne aucun résultat mais le statut 200 indique une réussite.
```

2022-03-11 15:33 UTC, NoemieFo commented on docs/fr/order.md
>  - une API pour récupérer la disponibilité du produit
Je sais pas si c'est très cohérent de commencer les phrases par "une API" alors qu'avant on avait directement le verbe correspondant à l'action

2022-03-11 15:33 UTC, NoemieFo commented on docs/order.md
> +- Adding an item to the cart produces 2 lines of details on the purchase order
```suggestion
- Adding an item to the cart produces two lines of details on the purchase order
```

2022-03-11 15:33 UTC, NoemieFo commented on docs/order.md
> +You may be surprised by the returned DNS zone (represented with 2 lines of details), since it was not added to the cart.
```suggestion
You may be surprised by the returned DNS zone (represented with two lines of details), since it was not added to the cart.
```

2022-03-11 15:42 UTC, benoitmasson commented on docs/fr/order.md
>  - une API pour récupérer la disponibilité du produit
tu as raison, je simplifie
(d'ailleurs, je l'avais fait en anglais)

2022-03-14 10:42 UTC, Thiht commented on docs/fr/order.md
>  ## Création du panier
je trouve un peu bizarre d'avoir Création du panier en titre niveau 2 et workflow plus haut en titre niveau 3. Faudrait pas plutôt passer à du niveau 4 ?

2022-03-14 10:44 UTC, Thiht commented on docs/fr/order.md
> +| domain    | oui    | ""     | le nom de domaine souhaité |
```suggestion
| domain    | oui    | ""     | Le nom de domaine souhaité |
```

2022-03-14 10:44 UTC, Thiht commented on docs/fr/order.md
> +err := client.Get(fmt.Sprintf("/order/cart/%s/domain?domain=foo.fr", cartID), &offers)
```suggestion
err := client.Get(fmt.Sprintf("/order/cart/%s/domain?domain=exemple.fr", cartID), &offers)
```

foo c'est pas parlant

2022-03-14 10:47 UTC, Thiht commented on docs/fr/order.md
> +1. L'_action_ : celle réalisable sur le domaine, ça peut être un "transfert" ou un "create"
```suggestion
1. `action` : celle réalisable sur le domaine, ça peut être un `transfer` ou un `create`
```

2022-03-14 10:51 UTC, Thiht commented on docs/fr/order.md
> +2. La _duration_ : ce champ représente l'unité de période sur laquelle il est possible de commander le domaine. Pour un domaine, P1Y (period 1 year) équivaut à une période d'un an, P2Y une période de
```suggestion
2. `duration` : ce champ représente l'unité de période au format ISO 8501 sur laquelle il est possible de commander le domaine. Pour un domaine, P1Y (**P**eriod **1** **Y**ear) équivaut à une période d'un an, P2Y une période de deux ans, etc.
```

2022-03-14 10:53 UTC, Thiht commented on docs/fr/order.md
> +3. L'_offerId_ : c'est le nom de l'offre qu'il faudra mettre lors de l'ajout du domaine dans le panier
```suggestion
3. `offerId` : c'est le nom de l'offre qu'il faudra mettre lors de l'ajout du domaine dans le panier
```

2022-03-14 10:54 UTC, Thiht commented on docs/fr/order.md
> +4. Le _pricing-mode_ : c'est le détail de l'offre qu'il faudra également mettre lors de l'ajout du domaine dans le panier
```suggestion
4. `pricingMode` : c'est le détail de l'offre qu'il faudra également mettre lors de l'ajout du domaine dans le panier
```

2022-03-14 10:57 UTC, Thiht requested changes
.

2022-03-14 10:57 UTC, Thiht commented on docs/fr/order.md
> +| create-default                               | Le domaine est libre et au prix standard
```suggestion
| `create-default`                               | Le domaine est libre et au prix standard                                                                                                                   |
```

2022-03-14 10:57 UTC, Thiht commented on docs/fr/order.md
> +| create-premium                               | Le domaine est libre mais est un premium. Son prix est variable d'un domaine à l'autre
```suggestion
| `create-premium`                               | Le domaine est libre mais est un premium. Son prix est variable d'un domaine à l'autre                                                                     |
```

2022-03-14 10:57 UTC, Thiht commented on docs/fr/order.md
> +| transfer-default                             | Le domaine n'est pas libre mais est transférable si vous en êtes le propriétaire. Son transfert est au prix standard
```suggestion
| `transfer-default`                             | Le domaine n'est pas libre mais est transférable si vous en êtes le propriétaire. Son transfert est au prix standard                                       |
```

2022-03-14 10:57 UTC, Thiht commented on docs/fr/order.md
> +| transfer-premium                             | Le domaine n'est pas libre mais est transférable si vous en êtes le propriétaire. C'est un domaine premium et son prix est variable d'un domaine à l'a
```suggestion
| `transfer-premium`                             | Le domaine n'est pas libre mais est transférable si vous en êtes le propriétaire. C'est un domaine premium et son prix est variable d'un domaine à l'autre |
```

2022-03-14 10:57 UTC, Thiht commented on docs/fr/order.md
> +| transfer-aftermarket1, transfer-aftermarket2 | Le domaine est libre via un marché secondaire. Son prix est variable d'un domaine à l'autre
```suggestion
| `transfer-aftermarket1`, `transfer-aftermarket2` | Le domaine est libre via un marché secondaire. Son prix est variable d'un domaine à l'autre                                                                |
```

2022-03-14 10:57 UTC, Thiht commented on docs/fr/order.md
> +Le deuxième, **déprécié et bientôt supprimé** consiste à analyser le couple pricing-mode/offerId.
Si c'est déprécié et bientôt supprimé faut pas le documenter, ça sert à rien. Surtout si la façon non dépréciée est documentée, autant donner qu'une façon de faire, le workflow est assez compliqué comme ça x)

2022-03-14 10:58 UTC, Thiht commented on docs/fr/order.md
> +| domain      | oui    |        | Le nom de domaine souhaité                                                                                                                       |
rajouter des backticks sur les lignes de la colonne Paramètre

2022-03-14 10:58 UTC, Thiht commented on docs/fr/order.md
> +| quantity    | non    |        | Pour le moment, seule la valeur "1" est autorisée                                                                                                |
```suggestion
| quantity    | non    |        | Seule la valeur "1" est autorisée                                                                                                |
```

2022-03-14 10:59 UTC, Thiht reviewed
.

2022-03-14 10:59 UTC, Thiht commented on docs/fr/order.md
> +| Paramètre   | Requis | Défaut | Description                                                                                                                                      |
Enlever la colonne Défaut vu qu'elle est vide

2022-03-14 10:59 UTC, benoitmasson commented on docs/fr/order.md
> +1. L'_action_ : celle réalisable sur le domaine, ça peut être un "transfert" ou un "create"
ok, fait en EN aussi

2022-03-14 11:00 UTC, Thiht commented on docs/fr/order.md
> +Met la valeur `itemId` de côté, tu en auras besoin pour la suite.
le tutoiement dans une doc, bof :D Faudrait reformuler ça à l'impersonnel ou au vouvoiement

2022-03-14 11:00 UTC, benoitmasson commented on docs/fr/order.md
> +err := client.Get(fmt.Sprintf("/order/cart/%s/domain?domain=foo.fr", cartID), &offers)
fait en EN aussi

2022-03-14 11:03 UTC, benoitmasson commented on docs/fr/order.md
>  ## Création du panier
niveau 4 non, car le niveau 2 permet d'ajouter des éléments dans la sidebar.

On pourrait se poser la question de mettre le Workflow en niveau 2, mais ça me choque pas comme c'est là, en conclusion de « API de commande »

2022-03-14 11:05 UTC, benoitmasson commented on docs/fr/order.md
> +2. La _duration_ : ce champ représente l'unité de période sur laquelle il est possible de commander le domaine. Pour un domaine, P1Y (period 1 year) équivaut à une période d'un an, P2Y une période de
+ EN

2022-03-14 11:07 UTC, benoitmasson commented on docs/fr/order.md
> +Le deuxième, **déprécié et bientôt supprimé** consiste à analyser le couple pricing-mode/offerId.
oui tu as raison

2022-03-14 11:13 UTC, benoitmasson commented on docs/fr/order.md
> +Met la valeur `itemId` de côté, tu en auras besoin pour la suite.
plutôt d'accord, mais pas d'avis tranché sur la question… cela étant, cette phrase est quand même assez abrupte, je reformule

2022-03-14 13:11 UTC, Thiht reviewed
.

2022-03-14 13:11 UTC, Thiht commented on docs/fr/order.md
>  ## Création du panier
ah oui c'est vrai que la sidebar affiche pas tous les niveaux

2022-03-14 13:26 UTC, Thiht commented on docs/fr/order.md
> +| ADMIN_ACCOUNT     | string                         | non               | Représente le nic OVHcloud qui pourra administrer le domaine et sera associé en tant qu'admin sur le Whois. Si vide, le nic
faudrait des backticks sur le contenu de la colonne Label, ça représente des valeurs de code

2022-03-14 13:26 UTC, Thiht commented on docs/fr/order.md
>  ::: danger Règles avancées lié aux contacts et aux noms de domaines
```suggestion
::: danger Règles avancées liées aux contacts et aux noms de domaines
```

2022-03-14 13:26 UTC, Thiht commented on docs/fr/order.md
> +Attention, cette API est conçue pour répondre aux besoins de la plupart des produits OVHcloud. Cependant, les noms de domaine ont la particularité d'avoir des règles beaucoup plus complexes concernan
```suggestion
Cette API est conçue pour répondre aux besoins de la plupart des produits OVHcloud. Les noms de domaine ont la particularité d'avoir des règles complexes concernant la valeur de certaines configurations, notamment sur les configurations `ADMIN_ACCOUNT`, `OWNER_CONTACT` ou encore `DOMAIN_CONFIG`, celles-ci étant liées aux règles de gestion des registres.
```

2022-03-14 13:26 UTC, Thiht commented on docs/fr/order.md
> +Pour cela, il existe d'autres API afin de décrire les informations nécessaire à un nom de domaine de manière précise. Ces APIs étant un peu complexe et utilisé également en dehors de la commande (com
```suggestion
Pour cela, il existe d'autres API afin de décrire les informations nécessaires à un nom de domaine de manière précise. Ces APIs correspondant à un usage avancé, et étant utilisées également en dehors de la commande (comme pour la mise à jour d'un contact), elles sont décrites en détail dans la section [Gestion des règles](rules).
```

2022-03-14 13:26 UTC, Thiht commented on docs/fr/order.md
> +Ici, le OWNER_CONTACT représente une API de "ressource", à savoir /me/contact ou plus précisement /domain/contact. Les APIs permettant de créer ces contacts sont décrites dans la section [Gestion des
```suggestion
Le `OWNER_CONTACT` représente une API de "ressource", à savoir `/me/contact` ou plus précisement `/domain/contact`. Les APIs permettant de créer ces contacts sont décrites dans la section [Gestion des contacts](contacts).
```

2022-03-14 13:26 UTC, Thiht commented on docs/fr/order.md
>  ::: warning Spécificité de la configuration OWNER_CONTACT
```suggestion
::: warning Spécificité de la configuration `OWNER_CONTACT`
```

2022-03-14 13:26 UTC, Thiht commented on docs/fr/order.md
> +Par exemple, pour l'obtention d'un .berlin, soit le contact registrant soit le contact admin doit résider à Berlin. Or cette API est en incapacité de décrire ce genre de règle.
J'enlèverais la phrase "Or cette API est en incapacité de décrire ce genre de règle", ça s'enchaine bien avec la suite

2022-03-14 13:26 UTC, Thiht commented on docs/fr/order.md
>  Cette étape est sans doute la plus importante du processus de commande et se fait via le call suivant.
> Cette étape est sans doute la plus importante

pas forcément d'accord avec ce genre de formulation, y a pas d'échelle d'importance dans les étapes.

2022-03-14 13:26 UTC, Thiht commented on docs/fr/order.md
> +| autoPayWithPreferredPaymentMethod | oui    | ""     | Permet de payer automatiquement le bon de commande avec le moyen de paiement par défaut du nic |
```suggestion
| `autoPayWithPreferredPaymentMethod` | oui    | ""     | Permet de payer automatiquement le bon de commande avec le moyen de paiement par défaut du nic |
```

2022-03-14 13:26 UTC, Thiht commented on docs/fr/order.md
> +| waiveRetractationPeriod           | oui    | ""     | Requis pour un nom de domaine. Il représente la renonciation au droit de rétractation          |
```suggestion
| `waiveRetractationPeriod`           | oui    | ""     | Requis pour un nom de domaine. Il représente la renonciation au droit de rétractation          |
```

2022-03-14 13:26 UTC, Thiht commented on docs/fr/order.md
> +Dans un premier temps, récupérons les moyens de paiement disponibles pour le bon de commande effectué plus tôt avec la [route suivante](https://api.ovh.com/console/#/me/order/%7BorderId%7D/availableR
je mettrais plutôt le lien sur la route, c'est plus logique

2022-03-14 13:26 UTC, Thiht commented on docs/fr/order.md
> +| orderId   | oui    | ""     | OrderId représente l'identifiant du BC obtenu lors de la [creation du bon de commande](#creation-du-bon-de-commande) |
```suggestion
| `orderId`   | oui    | ""     | `orderId` représente l'identifiant du BC obtenu lors de la [creation du bon de commande](#creation-du-bon-de-commande) |
```

2022-03-14 13:26 UTC, Thiht commented on docs/fr/order.md
> +| orderId       | oui                     | ""     | OrderId représente l'identifiant du BC obtenu lors de la [creation du bon de commande](#creation-du-bon-de-commande)                    |
backticks manquants dans la colonne Paramètre

2022-03-14 15:52 UTC, benoitmasson commented on docs/fr/order.md
> +Dans un premier temps, récupérons les moyens de paiement disponibles pour le bon de commande effectué plus tôt avec la [route suivante](https://api.ovh.com/console/#/me/order/%7BorderId%7D/availableR
j'ai un problème d'uniformisation là… au début, y avait pas les liens, du coup j'ai changé la mise en forme avec des triples ```, et du coup je peux pas mettre de lien autour…
c'est pour ça qu'ici j'ai déplacé le lien.

2 solutions donc pour corriger ça :
1. je reviens au truc initial, en ajoutant les liens partout
2. j'enlève tous les liens

(sachant qu'avec le truc officiel de doc, on aura un [truc pour ça](https://docs.dsi.ovh/display/CCC/Toolbox#Toolbox-API))

2022-03-16 10:54 UTC, closed without merging

2022-03-16 10:55 UTC, benoitmasson commented
moved to internal repository, for publication on official OVH documentation
https://docs.ovh.com/fr/domains/